full_prg2: full_prg2.c getemptyblocks.c setbits.c insertfile.c  vdread.c vdwrite.c 
	gcc full_prg2.c getemptyblocks.c setbits.c insertfile.c vdread.c vdwrite.c -o full_prg2  -lm

vdcreate: vdcreate.c write_to_buffer.c setbits.c vddriver.c
	gcc write_to_buffer.c vddriver.c  setbits.c vdcreate.c -o vdcreate -lm