full_prg2: full_prg2.c getemptyblocks.c setbits.c insertfile.c  vdread.c vdwrite.c 
	gcc full_prg2.c getemptyblocks.c setbits.c insertfile.c vdread.c vdwrite.c -o full_prg2  -lm

vdcreate: vdcreate.c write_to_buffer.c setbits.c vdwrite.c createfile.c
	gcc vdcreate.c write_to_buffer.c vdwrite.c  setbits.c createfile.c -o vdcreate -lm